# Generated by Django 4.1 on 2022-09-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectEmail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprovate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
