# Generated by Django 4.1 on 2022-09-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectEmail', '0002_ultimateverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleOrLink',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=255)),
            ],
        ),
    ]
