# Generated by Django 4.1 on 2022-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectEmail', '0003_scheduleorlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleorlink',
            name='type',
            field=models.CharField(default='schedule', max_length=255),
        ),
    ]
